### ISSUE TITLE
Any plan to implement in Windows version burp

### ISSUE THREAD

**Issue by gopinath6** [Lopseg/Jspathextractor#1]
Do you have  any plan to implement this extender Windows version burp. Cant install jsbeautifier in  windows.

**Comment by Lopseg** [comment]
Hi @gopinath6 ,
I'm already projecting the windows version!
Do you have any tip/hint/help to help me improve it?

Thanks!

**Comment by gopinath6** [comment]
Thanks. As of now ,no.I could not test it.

**Comment by Lopseg** [comment]
Sure !
I just released a new version that you can use within windows enviroment!
Please, don't forget to configure properly!
Check it out!

**Comment by gopinath6** [comment]
Working fine ! Thanks.
