### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Teicu** [Lopseg/Jspathextractor#2]
You can give some infos about how it comes installed on Mac? 

Thx

**Comment by Lopseg** [comment]
Hey, 
Since Mac is UNIX based, can you try to install it following the Linux steps in the README.md file and give me some feedback here ? 

Thanks!

**Comment by HD421** [comment]
Hello @Lopseg , I got jsbeautyfier installed on my Mac (by pip) but extension is still asking me for it.

> Scanning :ajax.googleapis.com
> 
> Urls or possible urls paths found:
> 
> /
> //
> 
> In order to this feature work properly install jsbeatifier on your system with the following commands:
> 
> sudo apt install jsbeautifier
> 
>

**Comment by Lopseg** [comment]
Hello @HD421 , Thanks for the feedback. The extension is printing the URL paths and working good as you can see, however it is asking for the jsbeautifier because there was some error in executing it in terminal. I've updated the error messages, for you know which error is ocurring, or is a file permission error or the extension can't execute the jsbeautifier using the "os" python lib. Can you please use this updated version of the extension and give me the feedback here ? 
 [https://github.com/Lopseg/Jsdir/blob/master/bp_jsscraper_linux.py](https://github.com/Lopseg/Jsdir/blob/master/bp_jsscraper_linux.pyl)

**Comment by xleng2019** [comment]
Hey,I have installed on mac,but I get some error is:
Error in writing to file at /tools/burp suit1.7/Jsdir-masterdb/files-beatified/*.js
Please check the write permissions of the folder/user

**Comment by hongweiren** [comment]
Hey I have installed on mac,but I get some error

Error in writing to file at /tools/burp suit1.7/Jsdir-masterdb/files-beatified/668.038-sec.cainiao.com.js
Please check the write permissions of the folder/user

**Comment by Lopseg** [comment]
Hey, thanks for the feedback. Have you already tried to change the folder permissions? If not, can you change it and try again?
Use commands like

`chmod 777 <directory where burp is trying to write>  `

**Comment by xleng2019** [comment]
> Hey, thanks for the feedback. Have you already tried to change the folder permissions? If not, can you change it and try again?
> Use commands like
> 
> `chmod 777 <directory where burp is trying to write> `

I have  changed the permission of tools directory by command 'chmod -R 777', but the error was still there. Should I run with root account?

**Comment by Lopseg** [comment]
Thanks for helping me find this bug. I have corrected this bug and more others involving the error messages that are displayed to the user, please test now and give me feedback if there is another bug. I'll be closing that issue now. Thank you again.
-Lopseg

**Comment by Lopseg** [comment]
> 
> 
> > Hey, thanks for the feedback. Have you already tried to change the folder permissions? If not, can you change it and try again?
> > Use commands like
> > `chmod 777 <directory where burp is trying to write> `
> 
> I have changed the permission of tools directory by command 'chmod -R 777', but the error was still there. Should I run with root account?

And no, it is not needed to run as root. Test with the new changes, thanks again.
